apiVersion: v1
kind: Service
metadata:
  labels:
    app: stf-triproxy-dev
  name: stf-triproxy-dev
spec:
  ports:
   - port: 7250
     targetPort: 7250
     name: bind-pub
   - port: 7260
     targetPort: 7260
     name: bind-dealer
   - port: 7270
     targetPort: 7270
     name: bind-pull
  type: LoadBalancer
  selector:
    app: stf-triproxy-dev
